version: '3.8'
name: nest-docker
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    init: true
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: 'yarn start:dev'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nest-docker-network
    depends_on:
      - db
      - cache
  cache:
    container_name: cache
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - nest-docker-network
  db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      - nest-docker-network
networks:
  nest-docker-network:
volumes:
  postgres-data:
  redis-data:
